#!/data/data/com.termux/files/usr/bin/bash
# read file and create INSERT statements for MySQL 
outfile='members.sql' 
IFS=','
while read lname fname address city state zip 
do 
    cat >> $outfile << end 
    VALUES ('$lname', '$fname', '$address', '$city', '$state', '$zip'); 
end
done < ${1}
