#!/data/data/com.termux/files/usr/bin/bash
# finding files in the PATH 
IFS=: 
for folder in $PATH 
do 
    echo "$folder:" 
    if [ -d $folder ]
    then 
        for file in $folder/* 
        do 
            if [ -x $file ] 
            then 
                echo " $file" 
            fi 
        done
    fi
done > output.txt
#
