#!/data/data/com.termux/files/usr/bin/bash
#
var1=10.46 
var2=43.67 
var3=33.2 
var4=71 
var5=$(bc << EO 
scale = 4 
a1 = ( $var1 * $var2) 
b1 = ($var3 * $var4) 
a1 + b1 
EO
)

echo The final answer for this mess is $var5
