#!/data/data/com.termux/files/usr/bin/bash
#

subshell="the command replace is `echo $BASH_SUBSHELL`"
echo $subshell

process_output="`ps -f --forest`"
echo $process_output

ps -f --forest

echo the script shell is $BASH_SUBSHELL

echo "the path is : $PATH"
