#!/data/data/com.termux/files/usr/bin/bash
#
my_variable="Full" 
# 
if test $my_variable 
then 
    echo "The $my_variable expression returns a True" 
# 
else echo "The $my_variable expression returns a False" 
fi
